version: '3.8' 

services:
  db:
    image: postgres:15-alpine 
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5433:5432"
    networks:
      - app-network 
    restart: always 
    
  backend:
    build:
      context: ./go-api 
      dockerfile: Dockerfile
    container_name: go_api_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      DB_HOST: db 
    ports:
      - "8080:8080"
    depends_on:
      - db 
    networks:
      - app-network
    restart: on-failure 

  frontend:
    build:
      context: ./react-frontend 
      dockerfile: Dockerfile
    container_name: react_frontend_service
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

volumes:
  db_data:

networks:
  app-network: 
    driver: bridge
